### ISSUE TITLE
[Internal] [Bug] RepeatMasker GFF "IndexError: list index out of range"

### ISSUE THREAD

**Issue by RamiyapriyaS** [CDCgov/tostadas#221]
**Index Error when running repeatmasker_liftoff.py script**&nbsp;  

Caused by:
  Process `TOSTADAS_WORKFLOW:TOSTADAS:REPEATMASKER_LIFTOFF:CONCAT_GFFS (3)` terminated with an error exit status (1)

Command executed:

  repeatmasker_liftoff.py         --repeatm_gff NY0007.fasta.out.gff         --liftoff_gff NY0007.liftoff-orig.gff         --refgff ref.MPXV.NC063383.v7.gff         --fasta NY0007.fasta          --sample_name NY0007

Command exit status:
  1

Command output:
  refgff is ref.MPXV.NC063383.v7.gff
  0 374
  ID=ITR-UPDATETAG-RPT1;rpt_type=long_terminal_repeat ID=ITR-UPDATETAG-RPT2;rpt_type=long_terminal_repeat

Command error:
  refgff is ref.MPXV.NC063383.v7.gff
  0 374
  ID=ITR-UPDATETAG-RPT1;rpt_type=long_terminal_repeat ID=ITR-UPDATETAG-RPT2;rpt_type=long_terminal_repeat
  Traceback (most recent call last):
    File "/scicomp/home-pure/rjd0/bin/repeatmasker_liftoff.py", line 133, in sample_info
      self.samp_end=int(samp_info[3].strip())
  IndexError: list index out of range
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/scicomp/home-pure/rjd0/bin/repeatmasker_liftoff.py", line 322, in <module>
      annotation_main()
    File "/scicomp/home-pure/rjd0/bin/repeatmasker_liftoff.py", line 85, in annotation_main
      new_gff=concat_gffs(args.liftoff_gff, repMannotation_prep.repM_prep_main(), LOannotation_prep.LO_prep_main(), ref_id, args.sample_name, args.outdir)
    File "/scicomp/home-pure/rjd0/bin/repeatmasker_liftoff.py", line 114, in repM_prep_main
      self.sample_info()
    File "/scicomp/home-pure/rjd0/bin/repeatmasker_liftoff.py", line 135, in sample_info
      raise Exception(f"A fourth element is not present in: {samp_info}")
  Exception: A fourth element is not present in: ['##date', '2024-11-18\n']

**Env**
 - Scicomp Environment
 - Running with Conda container

 **Steps to Replicate**
- Command: `nextflow run main.nf -profile test,conda --species virus --submission --annotation --sra --biosample --genbank --output_dir test --submission_config /scicomp/home-pure/rjd0/tostadas/bin/config_files/submission_config.yaml`
- User environment.yml file in repeatmasker_annotation step

Additional information: 
Output of `head` command on NY0007.fasta.out.gff
```
##gff-version 2
##date 2024-11-18
##sequence-region NY0007.fasta
NY0007  RepeatMasker    similarity      1       6418     0.1    -       .       Target "Motif:MPOX_ITR1" 1 6405
NY0007  RepeatMasker    similarity      6428    6436    27.6    +       .       Target "Motif:(TCATTA)n" 1 13
NY0007  RepeatMasker    similarity      6437    6469    14.4    +       .       Target "Motif:(TTA)n" 1 33
```

**Comment by RamiyapriyaS** [comment]
In the environment.yml file there is no version of repeatmasker specified. The pipeline defaults to using version 4.1.2-p1. The header of the output gff file created in versions <4.1.4 differ from later versions. 

Example of header when running with RepeatMasker 4.1.7
```
##gff-version 3
##sequence-region TX0001 1 197236
TX0001  RepeatMasker    dispersed_repeat        1       6451     0.1    -       .       ID=1;Target "Motif:MPOX_ITR1" 1 6422
TX0001  RepeatMasker    dispersed_repeat        6461    6469    27.6    +       .       ID=2;Target "Motif:(TCATTA)n" 1 13
```
