### ISSUE TITLE
[Internal] [Bug] UnboundLocalError: local variable 'sra_submission' referenced before assignment

### ISSUE THREAD

**Issue by jessicarowell** [CDCgov/tostadas#231]
ERROR ~ Error executing process > 'TOSTADAS_WORKFLOW:TOSTADAS:INITIAL_SUBMISSION:UPDATE_SUBMISSION (1)'

Caused by:
  Process `TOSTADAS_WORKFLOW:TOSTADAS:INITIAL_SUBMISSION:UPDATE_SUBMISSION (1)` terminated with an error exit status (1)

Error during update_submission:

Command executed:
  submission_new.py         --update         --submission_name DRR152972         --config_file submission_config.yaml          --metadata_file DRR152972.tsv         --species rsv         --output_dir  .         --fasta_file MZ568967.fasta                  --fastq1 DRR152972.R1.fastq.gz         --fastq2 DRR152972.R2.fastq.gz         --custom_metadata_file /scicomp/home-pure/ick4/02.scratch/metadata_custom_fields.json         --submission_mode ftp         --test                  --genbank --sra --biosample

Command exit status:
  1

Command output:
  Submission requested for genbank,biosample,sra
  Error: Missing required files for sra: ['DRR152972.R1.fastq.gz', 'DRR152972.R2.fastq.gz']
  Error: Missing required files for genbank: ['annotation_file (file not provided)']
  XML generated at ./DRR152972/biosample/submission.xml

Command error:
  /scicomp/home-pure/ick4/01.scripts/tostadas/bin/submission_new.py:380: UserWarning: DataFrame columns are not unique, some columns will be omitted.
    return self.metadata_df[available_columns].to_dict(orient='records')[0] if available_columns else {}
  Submission requested for genbank,biosample,sra
  Error: Missing required files for sra: ['DRR152972.R1.fastq.gz', 'DRR152972.R2.fastq.gz']
  Error: Missing required files for genbank: ['annotation_file (file not provided)']
  XML generated at ./DRR152972/biosample/submission.xml
  Traceback (most recent call last):
    File "/scicomp/home-pure/ick4/01.scripts/tostadas/bin/submission_new.py", line 1196, in <module>
      submission_main()
    File "/scicomp/home-pure/ick4/01.scripts/tostadas/bin/submission_new.py", line 139, in submission_main
      submission_objects = { 'biosample': biosample_submission, 'sra': sra_submission }
  UnboundLocalError: local variable 'sra_submission' referenced before assignment

Work dir:
  /scicomp/scratch/ick4/64/2f70f0db4867b8e2d1c7c9ea4fe5d7

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Place an :x: in a Box that Best Matches the Bug's Importance:**
* [] **1** - Most severe (a full-break in core function)
* [x] **2-4** - Moderate (break for a particular aspect/feature) (how integral is the broken feature?)
* [] **5** - Least severe (non-functional issue, such as inconsitency / error in documentation or administrative in nature)&nbsp;

**Please Complete the Following Information:**
 - OS: [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Version [e.g. 22]:
 - Run environment (container, cloud service, HPC, platform, etc.):

`nextflow run main.nf -profile test,singularity --species rsv --annotation false --submission true --output_dir test_rsv --submission_config /scicomp/home-pure/ick4/02.scratch/submission_config.yaml --meta_path ~/02.scratch/custom_test_metadata.xlsx --custom_fields_file ~/02.scratch/metadata_custom_fields.json `

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Concrete Instructions to Resolve the Bug or Helpful Resources to Reference? Screenshots or Logs?**

**Comment by jessicarowell** [comment]
Changed milestone to v4.2.0 because I can't replicate this error on dev. It's on the branch where I'm updating cloud path support.

**Comment by jessicarowell** [comment]
Alan got this error as well (his env is AWS).
Will try again on Monday to replicate it.

/tostadas/bin/submission_new.py:307: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  return self.metadata_df[available_columns].to_dict(orient='records')[0] if available_columns else {}
Traceback (most recent call last):
  File "/tostadas/bin/submission_new.py", line 1135, in <module>
    submission_main()
  File "/tostadas/bin/submission_new.py", line 139, in submission_main
    submission_objects = {'biosample': biosample_submission, 'sra': sra_submission}
UnboundLocalError: local variable 'sra_submission' referenced before assignment

**Comment by jessicarowell** [comment]
I'm still not able to replicate this, but I think it's related to the updates I already need to do on update_submission so I'm working on it now. Still planning this for milestone 4.2.0 but cloud paths will be bumped to 4.3.0.
