### ISSUE TITLE
-profile test fails when '/tostadas/submission_scripts/config_files/mpxv_config_kk.yaml' not found

### ISSUE THREAD

**Issue by erinyoung** [CDCgov/tostadas#4]
**Describe the bug**
One of the scripts calls a yml file that doesn't exist

**Impact**
Causes workflow to fail at 'with_submission:RUN_SUBMISSION:SUBMISSION'

**To Reproduce**
```
nextflow run tostadas/main.nf -profile test,conda
```

**Expected behavior**
I expected the workflow to run

**Screenshots**
```
executor >  local (5)
[3a/7c6910] process > RUN_UTILITY:VALIDATE_PARAMS    [100%] 1 of 1 ✔
[34/0f2ca5] process > RUN_UTILITY:CLEANUP_FILES      [100%] 1 of 1 ✔
[8a/36475d] process > with_submission:METADATA_VA... [100%] 1 of 1 ✔
[0e/76ccba] process > with_submission:LIFTOFF (1)    [100%] 1 of 1 ✔
[88/e15a33] process > with_submission:RUN_SUBMISS... [100%] 1 of 1, failed: 1 ✘
[-        ] process > with_submission:RUN_SUBMISS... -
[-        ] process > with_submission:RUN_SUBMISS... -
[-        ] process > with_submission:RUN_SUBMISS... -
Error executing process > 'with_submission:RUN_SUBMISSION:SUBMISSION (1)'

Caused by:
  Process `with_submission:RUN_SUBMISSION:SUBMISSION (1)` terminated with an error exit status (1)

Command executed:

  python3 /tostadas/bin/run_submission.py --validated_meta_path nf_test_results/validation_outputs --lifted_fasta_path nf_test_results/liftoff_outputs         --lifted_gff_                 path nf_test_results/liftoff_outputs --launch_dir /data --entry_flag false --submission_script /tostadas/submission_scripts/submission.py         --meta_path /tostadas/inpu                 t_files/MPXV_metadata_Sample_Run_1.xlsx --config mpxv_config_kk.yaml --nf_output_dir nf_test_results --submission_output_dir submission_outputs --update false         --bat                 ch_name batch1 --prod_or_test test --project_dir /tostadas

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/tostadas/bin/run_submission.py", line 178, in <module>
      submit_to_database.main()
    File "/tostadas/bin/run_submission.py", line 40, in main
      self.initial_submission()
    File "/tostadas/bin/run_submission.py", line 107, in initial_submission
      with open(self.parameters['config']) as sub_config:
  FileNotFoundError: [Errno 2] No such file or directory: '/tostadas/submission_scripts/config_files/mpxv_config_kk.yaml'

Work dir:
  /data/work/88/e15a339aad0fb744c2f2b858083a9b

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line



The command '/bin/sh -c nextflow run /tostadas/main.nf -profile test,conda' returned a non-zero code: 1

```

It doesn't look like this yml file exists in this repo. Was it taken out?

**Comment by ankushkgupta2** [comment]
Hey Erin, for the submission portion, it requires a custom configuration file with your personal information/paths as the submitter in order to run these processes. For these processes, to test out the dockerfile, I can try it out on my end since I have permissions and the config file set up on my end.
